version: 2 # use CircleCI 2.0
jobs: # a collection of steps
  build: # runs not using Workflows must have a `build` job as entry point
    parallelism: 1 # run one instance of this job in parallel
    docker: # run the steps with Docker
    # Find your ruby image: https://hub.docker.com/r/circleci/ruby/tags
      - image: circleci/ruby:2.7.1-node-browsers
        environment: # environment variables for primary container
          BUNDLE_JOBS: 3
          BUNDLE_RETRY: 3
          BUNDLE_PATH: vendor/bundle
          RAILS_ENV: test
          NODE_ENV: test
    steps: # a collection of executable commands
      - checkout # special step to check out source code to working directory

      - run:
          name: Configure Bundler
          command: |
            echo 'export BUNDLER_VERSION=$(cat Gemfile.lock | tail -1 | tr -d " ")' >> $BASH_ENV
            source $BASH_ENV
            gem install bundler

      - restore_cache:
          keys:
            - effective_orders

      - run:
          name: Install Bundle
          command: |
            bundle install

      - save_cache:
          key: effective_orders
          paths:
            - ./vendor/bundle

      - run:
          name: Run Unit Tests
          command: bundle exec rails test
